services:
  - type: web
    name: recruiting-agency
    runtime: python
    buildCommand: |
      pip install poetry
      poetry install --no-interaction --no-root
    startCommand: python start_render.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1" 